In [4]:
import pandas as pd
import numpy as np

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
file_path = "/content/drive/MyDrive/data.csv"

In [ ]:
df = pd.read_csv(file_path)
df.head()

In [7]:
df.type.value_counts()

normal        2203
aggressive    2203
Name: type, dtype: int64

In [8]:
df['aggressive'] = df['type'].apply(lambda x: 1 if x =='aggressive' else  0)
df.head()

comment        type  aggressive
0                                       يعطيكم الصحة      normal           0
1                                    عشي عندهما رجال      normal           0
2                         نبيك مغتصب الاطفال المنيوك  aggressive           1
3  بشير فار حبس خارج ثالثة ابتيدائي جاي اتناقش ما...      normal           0
4  مول القناة دزيزي جنيت تفرجت الفديو تاعك ولدي ت...      normal           0

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.comment,df.aggressive,test_size=0.2)

In [10]:
y_train[:4]

1746    0
4293    1
3946    1
4325    1
Name: aggressive, dtype: int64

In [11]:
# create bag of words using Countvectorizer
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train)
X_train_cv

<3524x15597 sparse matrix of type '<class 'numpy.int64'>'
	with 40730 stored elements in Compressed Sparse Row format>

In [12]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
X_train_cv.shape

(3524, 15597)

In [14]:
v.get_feature_names_out()[171]

'أشتم'

In [15]:
v.vocabulary_

{'نعيم': 12211,
 'الزعيم': 2157,
 'أسمر': 158,
 'ينجحش': 15418,
 'ينتقدوه': 15416,
 'الناس': 3346,
 'يقولك': 15288,
 'يهاجمو': 15470,
 'نعرفوهم': 12192,
 'يحبو': 14681,
 'المخنثين': 3062,
 'القح': 2759,
 'مخيب': 11008,
 'منظرها': 11660,
 'اللطف': 2920,
 'يتبع': 14553,
 'االذين': 483,
 'يعتدون': 15115,
 'كتاب': 9447,
 'حطب': 6325,
 'جهنم': 6101,
 'اعوذ': 1030,
 'بالله': 4005,
 'الشيطان': 2362,
 'الرجيم': 2093,
 'ربي': 7053,
 'يسترنا': 14938,
 'ويعافينا': 14284,
 'يحرقهم': 14699,
 'ويذلهم': 14256,
 'ذالهم': 6922,
 'ومفقرهم': 14072,
 'ومجوعهم': 14024,
 'كلاب': 9547,
 'المسيحين': 3152,
 'يحترمون': 14690,
 'المسلمين': 3146,
 'ولايفطرون': 13911,
 'امامهم': 3522,
 'ياكلاب': 14462,
 'يايهود': 14508,
 'تجاهرون': 4886,
 'بالمعصية': 4023,
 'وتأكلون': 13247,
 'رمضان': 7160,
 'الكريم': 2878,
 'ابتلانا': 502,
 'بجار': 4127,
 'عاصي': 8233,
 'ومذنب': 14033,
 'ومرتد': 14037,
 'تاكد': 4716,
 'للعيان': 10214,
 'الإمارات': 1253,
 'الجناح': 1763,
 'العسكري': 2546,
 'مخابرات': 10961,
 'الموساد': 3327,
 'الص

In [16]:
X_train_np = X_train_cv.toarray()
X_train_np[15]

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
np.where(X_train_np[15]!=0)

(array([ 1386,  2022,  2150,  2836,  2889,  3906,  4538,  4973,  5792,
         6141,  6661,  6663,  6664,  7209,  9597, 11839, 12049, 12338,
        13054, 13825, 13921, 14185, 15139, 15223, 15405]),)

In [18]:
v.get_feature_names_out()[4790]

'تتبت'

In [19]:
#train the naive bayes model
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [20]:
X_test_cv = v.transform(X_test)

In [21]:
#Evaluate Performance
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.77      0.81       455
           1       0.78      0.87      0.82       427

    accuracy                           0.82       882
   macro avg       0.82      0.82      0.82       882
weighted avg       0.82      0.82      0.82       882



In [22]:
comment = ['الحمدالله عنا بيسين في دارنا',
           'الواحد يفصل قفص حديد يعوم بيه',
           'برشا مشوى صيف السنا',
           'ايواش هاو توى ولينا نعفسو في الطبعة',
           'هي تشخر و زادت بففف']

comment_count = v.transform(comment)
model.predict(comment_count)

array([1, 0, 0, 1, 1])